// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtcic6NhGAMZHAqrji78csigmhhDcFSaI',
    appId: '1:1769255545:web:bcc3d7e824f34265db1aa8',
    messagingSenderId: '1769255545',
    projectId: 'nizhal-5016f',
    authDomain: 'nizhal-5016f.firebaseapp.com',
    storageBucket: 'nizhal-5016f.firebasestorage.app',
    measurementId: 'G-MD7V2TLLC9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzA_YBYqv1zojW5dKJq5MNZH0gDHyQc04',
    appId: '1:1769255545:android:3057c55a2eb8182cdb1aa8',
    messagingSenderId: '1769255545',
    projectId: 'nizhal-5016f',
    storageBucket: 'nizhal-5016f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXDW7Hn4v3suoQ_AhL5yxFqI-PhTjCgvc',
    appId: '1:1769255545:ios:bb323148669dfb1adb1aa8',
    messagingSenderId: '1769255545',
    projectId: 'nizhal-5016f',
    storageBucket: 'nizhal-5016f.firebasestorage.app',
    iosBundleId: 'com.example.nizhal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXDW7Hn4v3suoQ_AhL5yxFqI-PhTjCgvc',
    appId: '1:1769255545:ios:bb323148669dfb1adb1aa8',
    messagingSenderId: '1769255545',
    projectId: 'nizhal-5016f',
    storageBucket: 'nizhal-5016f.firebasestorage.app',
    iosBundleId: 'com.example.nizhal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtcic6NhGAMZHAqrji78csigmhhDcFSaI',
    appId: '1:1769255545:web:593ef9cf30576bd3db1aa8',
    messagingSenderId: '1769255545',
    projectId: 'nizhal-5016f',
    authDomain: 'nizhal-5016f.firebaseapp.com',
    storageBucket: 'nizhal-5016f.firebasestorage.app',
    measurementId: 'G-JGNPHX5Y58',
  );
}
